<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Version>0.1.3</Version>
    <AssemblyName>RegionShare</AssemblyName>
    <Product>RegionShare</Product>
    <ApplicationIcon Condition="Exists('Assets\RegionShare.ico')">Assets\RegionShare.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.6.2" />
    <PackageReference Include="Vortice.DXGI" Version="3.6.2" />
  </ItemGroup>

</Project>
